create table horses (
    bloodline varchar(100),
    breed_type varchar(100),
    career_first INT,
    career_second INT,
    career_third INT,
    genotype VARCHAR(50),
    hashinfo_color VARCHAR(100),
    hashinfo_hexcode VARCHAR(100),
    hashinfo_name VARCHAR(1000),
    horse_id INT,
    horse_type  VARCHAR(100),
    img_url VARCHAR(100) ,
    number_of_races  INT, 
    owner  VARCHAR(100),
    super_coat  TINYINT,
    tx  VARCHAR(100),
    tx_date  VARCHAR(100),
    win_rate  INT,
    PRIMARY KEY(horse_id)
);

create table races_results (
    race_id VARCHAR(100),
    horse_id INT, 
    finish_time VARCHAR(100),
    final_position VARCHAR(100),
    name VARCHAR(1000) ,
    gate VARCHAR(1000), 
    owner_address VARCHAR(1000),
    bloodline VARCHAR(1000),
    gender VARCHAR(100),
    breed_type VARCHAR(100),
    gen VARCHAR(100) ,
    races VARCHAR(100) , 
    coat VARCHAR(100),
    win_rate VARCHAR(100),
    career VARCHAR(100), 
    hex_color VARCHAR(100),
    img_url VARCHAR(100),
    class INT, 
    stable_name VARCHAR(1000) 
);

create table races (
city varchar(100),
class INT,
country_code varchar(10),
fee FLOAT,
length INT,
name VARCHAR(1000),
prizepool_first VARCHAR(1000),
prizepool_second VARCHAR(1000),
prizepool_third  VARCHAR(1000),
prizepool_total VARCHAR(1000),
race_id VARCHAR(20),
start_time VARCHAR(100),
status  VARCHAR(100),
weather VARCHAR(100),
PRIMARY KEY(race_id)
);

create table stables (
    bloodline varchar(100),
    breed_type varchar(100),
    career_first INT,
    career_second INT,
    career_third INT,
    genotype VARCHAR(50),
    hashinfo_color VARCHAR(100),
    hashinfo_hexcode VARCHAR(100),
    hashinfo_name VARCHAR(1000),
    horse_id INT,
    horse_type  VARCHAR(100),
    img_url VARCHAR(100) ,
    number_of_races  INT, 
    owner  VARCHAR(100),
    super_coat  TINYINT,
    tx  VARCHAR(100),
    tx_date  VARCHAR(100),
    win_rate  INT,
    PRIMARY KEY(horse_id)
);